# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transact.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransact.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0btypes.proto\"3\n\nPutRequest\x12\x11\n\x03key\x18\x01 \x01(\x0b\x32\x04.Key\x12\x12\n\x04\x62ins\x18\x03 \x03(\x0b\x32\x04.Bin\"B\n\nGetRequest\x12\x11\n\x03key\x18\x01 \x01(\x0b\x32\x04.Key\x12!\n\x0b\x62inSelector\x18\x02 \x01(\x0b\x32\x0c.BinSelector\"?\n\x0b\x42inSelector\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.BinSelectorType\x12\x10\n\x08\x62inNames\x18\x02 \x03(\t\"~\n\x13VectorSearchRequest\x12\x17\n\x05index\x18\x01 \x01(\x0b\x32\x08.IndexId\x12\x1c\n\x0bqueryVector\x18\x02 \x01(\x0b\x32\x07.Vector\x12\r\n\x05limit\x18\x03 \x01(\r\x12!\n\x0b\x62inSelector\x18\x04 \x01(\x0b\x32\x0c.BinSelector*3\n\x0f\x42inSelectorType\x12\x07\n\x03\x41LL\x10\x00\x12\x08\n\x04NONE\x10\x01\x12\r\n\tSPECIFIED\x10\x02\x32\x91\x01\n\x08Transact\x12,\n\x03Put\x12\x0b.PutRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x1d\n\x03Get\x12\x0b.GetRequest\x1a\x07.Record\"\x00\x12\x38\n\x0cVectorSearch\x12\x14.VectorSearchRequest\x1a\x0e.RecordWithKey\"\x00\x30\x01\x42=\n\x1b\x63om.aerospike.vector.clientP\x01Z\x1c\x61\x65rospike.com/vector/protos/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transact_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.aerospike.vector.clientP\001Z\034aerospike.com/vector/protos/'
  _globals['_BINSELECTORTYPE']._serialized_start=374
  _globals['_BINSELECTORTYPE']._serialized_end=425
  _globals['_PUTREQUEST']._serialized_start=60
  _globals['_PUTREQUEST']._serialized_end=111
  _globals['_GETREQUEST']._serialized_start=113
  _globals['_GETREQUEST']._serialized_end=179
  _globals['_BINSELECTOR']._serialized_start=181
  _globals['_BINSELECTOR']._serialized_end=244
  _globals['_VECTORSEARCHREQUEST']._serialized_start=246
  _globals['_VECTORSEARCHREQUEST']._serialized_end=372
  _globals['_TRANSACT']._serialized_start=428
  _globals['_TRANSACT']._serialized_end=573
# @@protoc_insertion_point(module_scope)