# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector-db.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvector-db.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0btypes.proto\"\x0e\n\x0c\x41\x62outRequest\" \n\rAboutResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"\x17\n\tClusterId\x12\n\n\x02id\x18\x01 \x01(\x04\"\x14\n\x06NodeId\x12\n\n\x02id\x18\x01 \x01(\x04\">\n\x0eServerEndpoint\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\r\n\x05isTls\x18\x03 \x01(\x08\"8\n\x12ServerEndpointList\x12\"\n\tendpoints\x18\x01 \x03(\x0b\x32\x0f.ServerEndpoint\"\x96\x01\n\x14\x43lusterNodeEndpoints\x12\x37\n\tendpoints\x18\x01 \x03(\x0b\x32$.ClusterNodeEndpoints.EndpointsEntry\x1a\x45\n\x0e\x45ndpointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.ServerEndpointList:\x02\x38\x01\"I\n\x1b\x43lusterNodeEndpointsRequest\x12\x19\n\x0clistenerName\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_listenerName\"*\n\x0fOwnedPartitions\x12\x17\n\x0fownedPartitions\x18\x01 \x03(\x04\"\x90\x01\n\x11\x43lusterPartitions\x12\x36\n\npartitions\x18\x01 \x03(\x0b\x32\".ClusterPartitions.PartitionsEntry\x1a\x43\n\x0fPartitionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.OwnedPartitions:\x02\x38\x01\x32/\n\x05\x41\x62out\x12&\n\x03Get\x12\r.AboutRequest\x1a\x0e.AboutResponse\"\x00\x32\x85\x02\n\x0b\x43lusterInfo\x12.\n\tGetNodeId\x12\x16.google.protobuf.Empty\x1a\x07.NodeId\"\x00\x12\x34\n\x0cGetClusterId\x12\x16.google.protobuf.Empty\x1a\n.ClusterId\"\x00\x12L\n\x13GetClusterEndpoints\x12\x1c.ClusterNodeEndpointsRequest\x1a\x15.ClusterNodeEndpoints\"\x00\x12\x42\n\x12GetOwnedPartitions\x12\x16.google.protobuf.Empty\x1a\x12.ClusterPartitions\"\x00\x42=\n\x1b\x63om.aerospike.vector.clientP\x01Z\x1c\x61\x65rospike.com/vector/protos/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_db_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.aerospike.vector.clientP\001Z\034aerospike.com/vector/protos/'
  _CLUSTERNODEENDPOINTS_ENDPOINTSENTRY._options = None
  _CLUSTERNODEENDPOINTS_ENDPOINTSENTRY._serialized_options = b'8\001'
  _CLUSTERPARTITIONS_PARTITIONSENTRY._options = None
  _CLUSTERPARTITIONS_PARTITIONSENTRY._serialized_options = b'8\001'
  _globals['_ABOUTREQUEST']._serialized_start=61
  _globals['_ABOUTREQUEST']._serialized_end=75
  _globals['_ABOUTRESPONSE']._serialized_start=77
  _globals['_ABOUTRESPONSE']._serialized_end=109
  _globals['_CLUSTERID']._serialized_start=111
  _globals['_CLUSTERID']._serialized_end=134
  _globals['_NODEID']._serialized_start=136
  _globals['_NODEID']._serialized_end=156
  _globals['_SERVERENDPOINT']._serialized_start=158
  _globals['_SERVERENDPOINT']._serialized_end=220
  _globals['_SERVERENDPOINTLIST']._serialized_start=222
  _globals['_SERVERENDPOINTLIST']._serialized_end=278
  _globals['_CLUSTERNODEENDPOINTS']._serialized_start=281
  _globals['_CLUSTERNODEENDPOINTS']._serialized_end=431
  _globals['_CLUSTERNODEENDPOINTS_ENDPOINTSENTRY']._serialized_start=362
  _globals['_CLUSTERNODEENDPOINTS_ENDPOINTSENTRY']._serialized_end=431
  _globals['_CLUSTERNODEENDPOINTSREQUEST']._serialized_start=433
  _globals['_CLUSTERNODEENDPOINTSREQUEST']._serialized_end=506
  _globals['_OWNEDPARTITIONS']._serialized_start=508
  _globals['_OWNEDPARTITIONS']._serialized_end=550
  _globals['_CLUSTERPARTITIONS']._serialized_start=553
  _globals['_CLUSTERPARTITIONS']._serialized_end=697
  _globals['_CLUSTERPARTITIONS_PARTITIONSENTRY']._serialized_start=630
  _globals['_CLUSTERPARTITIONS_PARTITIONSENTRY']._serialized_end=697
  _globals['_ABOUT']._serialized_start=699
  _globals['_ABOUT']._serialized_end=746
  _globals['_CLUSTERINFO']._serialized_start=749
  _globals['_CLUSTERINFO']._serialized_end=1010
# @@protoc_insertion_point(module_scope)