{
 "title": "Aerospike Proximus Cluster View",
 "description": "Proximus View dashboard helps visualise indexed, query success/error in selected proximus cluster",
 "tags": [
  "Monitoring",
  "vectors"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_proximus_heartbeats_sent,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_proximus_heartbeats_sent{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(aerospike_proximus_heartbeats_sent{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},instance)"
    }
   },
   {
    "name": "index",
    "label": "index",
    "query": {
     "query": "label_values(aerospike_proximus_requests,index)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<b>NOTE: This dashboard display details only from Proximus server, to know about underlying Aerospike Server you need to use other dashboards like Cluster View, Namespace View etc.,</b>"
   }
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proximus Cluster Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(aerospike_proximus_cluster_size{cluster_name=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Index Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (index) (aerospike_proximus_requests{index=~\"$index\", type=~\"update\", update_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_proximus_requests{index=~\"$index\", type=~\"query\", query_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "Succes"
      },
      {
       "expr": "sum(aerospike_proximus_requests{index=~\"$index\", type=\"query\", query_type=\"client\",status=\"error\",cluster_name=\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (aerospike_proximus_connections{cluster_name=~\"$cluster\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 11, "y": 3 },
     "targets": [
      {
       "expr": "sum by (status) (aerospike_proximus_connections{cluster_name=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Success (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "irate(aerospike_proximus_requests{index=~\"$index\", type=~\"query\", query_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) ",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Cache Hits Ratio (%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "100* rate(aerospike_proximus_index_cache_hits{cluster_name=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])/(rate(aerospike_proximus_index_cache_hits{cluster_name=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) + rate(aerospike_proximus_index_cache_misses{cluster_name=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) + 1)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Median Query Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "aerospike_proximus_requests{index=~\"$index\",type=~\"query\", query_type=~\"client\" ,quantile=\"0.5\",cluster_name=~\"$cluster\"} * 1000 ",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Median Index Update Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "\naerospike_proximus_requests{index=~\"$index\",type=\"update\", update_type=~\"client\" ,quantile=~\"0.5\",cluster_name=~\"$cluster\", instance=~\"$instance\"} * 1000 ",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Queries</b></p>"
     }
    },
    {
     "title": "Query Proxy-in (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "irate(aerospike_proximus_requests{type=\"query\", index=~\"$index\", query_type=~\"proxy-in\", status=\"success\",cluster_name=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Query Local (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "rate(aerospike_proximus_requests{type=\"query\", index=~\"$index\", query_type=\"local\", status=\"success\",cluster_name=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Query Error (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(aerospike_proximus_requests{index=~\"$index\", type=\"query\", query_type=\"client\",status=\"error\",cluster_name=\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) ",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Query Proxy-out (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "rate(aerospike_proximus_requests{type=\"query\", index=~\"$index\", query_type=~\"proxy-out\", status=\"success\",cluster_name=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Index</b></p>"
     }
    },
    {
     "title": "Indexd Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "aerospike_proximus_requests{index=~\"$index\", type=~\"update\", update_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\"} ",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Index Update Success (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "irate(aerospike_proximus_requests{index=~\"$index\",type=\"update\", update_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) ",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Index Update Proxy-in (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "\nrate(aerospike_proximus_requests{type=\"update\", index=~\"$index\", update_type=\"proxy-in\", status=\"success\", cluster_name=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Index Update Error (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "\nrate(aerospike_proximus_requests{index=~\"$index\", type=\"update\", update_type=\"client\",status=\"error\", cluster_name=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    },
    {
     "title": "Index Update Error (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "rate(aerospike_proximus_requests{index=~\"$index\", type=~\"update\", update_type=~\"client\",status=~\"error\", cluster_name=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{index}}"
      }
     ]
    }
   ]
  }
 ]
}