# quote-search Dockfile
FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y python3 python3-pip \
    && pip3 install setuptools sql

RUN mkdir /quote-search
COPY ./quote-search /quote-search
WORKDIR /quote-search
RUN python3 -m pip install -r requirements.txt --extra-index-url https://aerospike.jfrog.io/artifactory/api/pypi/aerospike-pypi-dev/simple 

ENTRYPOINT ["waitress-serve"]
CMD ["--host=0.0.0.0", "--port=8080", "--threads=32", "quote_search:app"]