# Prism Dockfile
FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y python3 python3-pip \
    && pip3 install setuptools sql

RUN mkdir /prism
COPY ./prism /prism
WORKDIR /prism
RUN python3 -m pip install -r requirements.txt

ENTRYPOINT ["waitress-serve"]
CMD ["--host=0.0.0.0", "--port=8080", "--threads=32", "prism:app"]